# Site settings
title: A Data Storyteller
email: support@landak.tech
url: https://www.landak.tech
description: "A private consultant in business and data analytics."
keywords: "business analytics, data analytics, data, analytics, business, business intelligence, visual analytics, descriptive analytics, diagnostic analytics, predictive analytics, prescriptive analytics, affordable, remote work"
skills: "Data Analytics - BI Development - Python Development"
meta_author: Landak Analytics
logo: img/logo.svg
about: 
  paragraph1: Landak Analytics will tell you stories about your data, gain insight, make decisions and plan actions upon it. We provide high quality, on-time, and on-budget data analytics services for business.
  paragraph2: We aim to help entrepreneurs, small-medium enterprises & startups to implement data analytics from their early stage, furthermore use it to solve their problem and expand their business.

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 056DD9 #80B3FF
  primary-rgb: "5,109,217" #"24,288,156" #"128,179,255"
  secondary: 333333 #FD6E8A
  secondary-dark: 3D3D3D #A2122F

# Footer settings
footer:
  copyright: Landak Analytics
  location: Indonesia
  social: Around the Web
  notes: Special Services

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company/landak/
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: instagram
    url: 
  - title: github
    url: https://github.com/landak-tech

# Postal address (add as many lines as necessary)
address:
  - line: Greater Surabaya Area
  - line: East Java
  - line: (Available for remote work)

# Notes content
notes:  We offer a special rate to a certain type of non-profit organization, please feel free to fill these <a href="{{ site.googleform }}">form</a> and we'll get back to you as soon as possible to validate your eligibility.

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""


#for non profit organization
googleform: https://forms.gle/35foKucPRs5veAwu7
